### ISSUE TITLE
"Can not determine location to install CA certificate on Linux Mint 21.3"

### ISSUE THREAD

**Issue by GijsvandenHoven** [tmds/linux-dev-certs#13]
I was wondering if this might be an error, as Mint is derived from Ubuntu which is derived from Debian.

I poked around the code a bit, and I think I might even know why: in `OSFlavor.cs`, `isDebianLike` is set with EnsureIds().

This reads the /etc/os-release file and scans the ID and ID_LIKE fields.

This file looks like this on my computer:

```
NAME="Linux Mint"
VERSION="21.3 (Virginia)"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 21.3"
VERSION_ID="21.3"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=virginia
UBUNTU_CODENAME=jammy
```

So I suspect this is failing because unfortunately, "ubuntu debian"  does not match "debian" :smile:

**Comment by tmds** [comment]
Thanks for the bug report, and finding the root cause!

Can you give this build a try and verify it works?
```
dotnet tool update -g linux-dev-certs --prerelease --add-source https://www.myget.org/F/tmds/api/v3/index.json
```

**Comment by GijsvandenHoven** [comment]
Thank you for the swift fix! It looks like it works:

![image](https://github.com/tmds/linux-dev-certs/assets/60928209/0bb80cbf-0799-48c2-8359-461ba905464b)

**Comment by GijsvandenHoven** [comment]
I have played around with it a bit, and everything seems to be working.

At first I had some mysterious CORS problems sending requests to the ASP.NET with a frontend over localhost, but rebooting fixed this. You mentioned doing this in a Github issue where I originally found this tool, so I owe you my thanks twice now :+1: 

The only difference I can find in logs booting up the application between LM and a Win10 VM is that I am still getting this warning:

```
Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer[8]
      The ASP.NET Core developer certificate is not trusted. For information about trusting the ASP.NET Core developer certificate, see https://aka.ms/aspnet/https-trust-dev-cert.
``` 
But despite aspnetcore telling me this, it might not actually be the case. 
I can find no evidence of the certificate not being trusted when using the ASP.NET backend I work on.

If you're familiar with this log persisting despite the tool creating a certificate, then I assume it can be safely ignored.

**Comment by tmds** [comment]
> I have played around with it a bit, and everything seems to be working.

Great! I will include this in a release in the near future.

> If you're familiar with this log persisting despite the tool creating a certificate, then I assume it can be safely ignored.

Yes, you can ignore it. There is an open PR to get rid of that message: https://github.com/dotnet/aspnetcore/pull/55335.
