### ISSUE TITLE
Add support for Arch Linux.

### ISSUE THREAD

**Issue by chivongv** [tmds/linux-dev-certs#17]
I got this issue when I was trying to install dev certs on Arch linux. I found similar issue in https://github.com/tmds/linux-dev-certs/issues/13. Any chance to support Arch linux?

This is what /etc/os-release looked on my computer:

```
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
```

**Comment by chivongv** [comment]
I will be glad to contribute! Let me dig into this. 😃

**Comment by chivongv** [comment]
I managed to build and install the certificates with the changes in [PR](https://github.com/tmds/linux-dev-certs/pull/18) but it seemed not working correctly. I ran my .Net 8 webapp with https and I still got the warning message `The ASP.NET Core developer certificate is not trusted. For information about trusting the ASP.NET Core developer certificate, see https://aka.ms/aspnet/https-trust-dev-cert.`. In addition, when I ran command `curl https://localhost:{port}` I got the error message 

> curl: (60) SSL certificate problem: self-signed certificate
> More details here: https://curl.se/docs/sslcerts.html
> curl failed to verify the legitimacy of the server and therefore could not establish a secure connection to it.

Do you have any ideas?

**Comment by chivongv** [comment]
It should work now. I tested on Firefox, Brave and Chrome. However, the messages are still there. Curl gives 

> curl: (35) OpenSSL/3.3.0: error:0200008A:rsa routines::invalid padding

**Comment by tmds** [comment]
Fixed by https://github.com/tmds/linux-dev-certs/pull/18.

**Comment by tmds** [comment]
This is part of the 0.2.0 version which was just uploaded to nuget.org.
