### ISSUE TITLE
Add Gentoo Support

### ISSUE THREAD

**Issue by babaruh** [tmds/linux-dev-certs#21]
I got this issue when I was trying to install `dotnet dev-certs https` on Gentoo. It's kinda similar to Debian based linux so I hope it's possible to add support for Gentoo.

```
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
VERSION_ID="2.15"
```

Open to provide files or configurations as needed :)

**Comment by tmds** [comment]
@babaruh do you want to give a shot at implementing this?

This PR is a good example of how to add a new distro: https://github.com/tmds/linux-dev-certs/pull/18/files

For things that are the same as Debian, you can share code branches: `if (OSFlavor.IsDebianLike || OSFlavor.IsGentooLike)`.

**Comment by babaruh** [comment]
I have already added support. 

Firefox doesn't accept the generated certificate, I'll have to think about what's wrong with it.
![image](https://github.com/tmds/linux-dev-certs/assets/94543091/c8363bd5-ff17-45bc-9c87-7f6b394bdccf)
![image](https://github.com/tmds/linux-dev-certs/assets/94543091/99ab5489-c337-4fbc-8b81-f597fc142d24)

 
I also may need to add support for LibreWolf (my main browser).

**Comment by babaruh** [comment]
@tmds I don't have permission to commit into https://github.com/tmds/linux-dev-certs.git

**Comment by tmds** [comment]
You need to fork the repo to your account, make the changes on a branch in your fork, and then open up a pull request against this repo.

**Comment by tmds** [comment]
Fixed by https://github.com/tmds/linux-dev-certs/pull/22.

**Comment by tmds** [comment]
This is part of 0.3.0 which was just released on nuget.org.
