### ISSUE TITLE
Log message says installing CA cert when installing dev cert

### ISSUE THREAD

**Issue by DamianEdwards** [tmds/linux-dev-certs#26]
The following log message seems incorrect? It's saying it's installing the CA cert but it's installing the generated HTTPS dev cert right?

https://github.com/tmds/linux-dev-certs/blob/48ed17400be8bdc841e04d95687b607a41fe58e1/src/linux-dev-certs/CertificateManager.cs#L64-L70

**Comment by tmds** [comment]
@DamianEdwards you are correct, the message should say dev cert.
