### ISSUE TITLE
Works fine for "normal" web projects but not for Aspire

### ISSUE THREAD

**Issue by MichaelHochriegl** [tmds/linux-dev-certs#28]
Greetings,

I use this tool on all my dev machines and it works great for "normal" ASP.Net Core web projects, e.g. API and Blazor, however when I try to run an Aspire app I can't reach the dashboard although the AppHost is running fine.

Is the certificate management somehow different on an Aspire project?

**Comment by tmds** [comment]
> I can't reach the dashboard

What does this mean? What message does your browser show?

> Is the certificate management somehow different on an Aspire project?

No. Aspire uses the same developer certificate as other ASP.NET Core sites.

**Comment by MichaelHochriegl** [comment]
Sorry for the late reply, but I found the culprit. I had the .Net9 Preview installed and it seems like it completely borked my Aspire workload. I don't quite get why this resulted in an exception where the SSL cert was mentioned, but after I cleanly removed the .Net9 Preview everything works fine.

Sorry for the fuss
