### ISSUE TITLE
Install fails. .NET not installed?

### ISSUE THREAD

**Issue by dex91** [tmds/linux-dev-certs#30]
Hi there,

after successfully installing .NET 8 and also ASPNetCore to `/root/.dotnet` and adding all PATH-Vars to .profile (re-login to take effect) i can run `dotnet tool update -g linux-dev-certs` and getting a successful output.

BUT when i run `dotnet linux-dev-certs install` it fails and tells me that .NET isnt installed.

![image](https://github.com/user-attachments/assets/b31e5f21-eac3-44d4-81f1-e9aae7761739)

EDIT: however i use root or my personal development account, both tell me the same.

**Comment by dex91** [comment]
I figured out why.. You need to set `export DOTNET_ROOT=$HOME/.dotnet` in `.profile`, too. So this tool here can find .NET
I only had riders and jetbrains toolbox generated export-vars in both user-profiles.

It should be added to the readme, that this export above needs to be set.

**Comment by karpikpl** [comment]
I'm having the same issue but changing .profile did not help

**Comment by arizon-dread** [comment]
@karpikpl did you `source ~/.profile` before trying the command again after adding the `export DOTNET_ROOT=$HOME/.dotnet` to your `~/.profile`?

**Comment by karpikpl** [comment]
I think I did. What worked for me though is running the app from sources (`dotnet run`) rather than as a dotnet tool
