### ISSUE TITLE
"You must install .NET to run this application" error on Ubuntu 22.04 with .NET 8.0.8 SDK installed

### ISSUE THREAD

**Issue by bairog** [tmds/linux-dev-certs#33]
Hello.
I have Ubuntu 22.04 with .NET 8.0.8 SDK installed.
Installing linux-dev-certs tool `dotnet tool update -g linux-dev-certs` and on `dotnet linux-dev-certs install` I got an error:
![image](https://github.com/user-attachments/assets/e35cc923-2f1a-456e-a629-df868952b2ef)
As you can see dotnet itself see both runtimes and sdk, but linux-dev-certs tool cannot.
What should I do?

**Comment by tmds** [comment]
I don't think the issue is specific to `linux-dev-certs` and that you'll see it with any tool you install and try to run.

Can you share the output of:
```
COREHOST_TRACE=1 dotnet linux-dev-certs install
```

**Comment by tmds** [comment]
@bairog is it working for you in the meanwhile?

**Comment by bairog** [comment]
I've reinstalled .NET SDK 8.0 and suddenly it started working. Thank you.
